spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"  # Fix the typo in OPTIONS
              allowedHeaders: "*"
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**
        - id: r3
          uri: http://localhost:8083/
          predicates:
            - Path=/orders/**
    discovery:
      enabled: false
server:
  port: 8888

